---
channel: stable
addons:
  caddy-2:
    repository: einschmidt/addon-caddy-2
    target: caddy-2
    image: ghcr.io/einschmidt/caddy-2/{arch}
  yarr:
    repository: einschmidt/app-yarr
    target: yarr
    image: ghcr.io/einschmidt/yarr
  freshrss:
    repository: einschmidt/addon-freshrss
    target: freshrss
    image: ghcr.io/einschmidt/freshrss/{arch}
  pocket-id:
    repository: einschmidt/addon-pocket-id
    target: pocket-id
    image: ghcr.io/einschmidt/pocket-id/{arch}
  authelia:
    repository: einschmidt/addon-authelia
    target: authelia
    image: ghcr.io/einschmidt/authelia/{arch}
  fusion:
    repository: einschmidt/app-fusion
    target: fusion
    image: ghcr.io/einschmidt/fusion
  lldap:
    repository: einschmidt/app-lldap
    target: lldap
    image: ghcr.io/einschmidt/lldap
